# Tokyo Night
background #1a1b26
foreground #a9b1d6
selection_background #28344a
selection_foreground #a9b1d6
url_color #73daca
cursor #c0caf5
cursor_text_color #1a1b26

# Border
active_border_color #7aa2f7
inactive_border_color #3b4261
bell_border_color #e0af68

# Tab bar
tab_bar_style powerline
active_tab_foreground #1a1b26
active_tab_background #7aa2f7
inactive_tab_foreground #a9b1d6
inactive_tab_background #1e2030
tab_bar_edge bottom

# Colors
color0  #1d202f
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

# Font
font_family      JetBrains Mono Nerd Font
bold_font        JetBrains Mono Nerd Font Bold
italic_font      JetBrains Mono Nerd Font Italic
bold_italic_font JetBrains Mono Nerd Font Bold Italic
font_size 11.0

# Layout
window_padding_width 8
hide_window_decorations no
confirm_os_window_close 0

# Scrollback
scrollback_lines 10000
scrollback_pager_history_size 1000

# Mouse
mouse_hide_wait 2.0
url_color #7aa2f7
open_url_with default

# Performance
repaint_delay 10
sync_to_monitor yes
