exec-once = waybar
exec-once = dunst
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = swww init && swww img ~/.config/wallpapers/tokyo-night.png
exec-once = greenclip daemon
exec-once = hypridle
