windowrulev2 = workspace 2 silent, class:^(firefox|Firefox|org\.mozilla\.firefox)$
windowrulev2 = float, class:^(mplayer2|GParted|Toplevel|pavucontrol|org\.pulseaudio\.pavucontrol|org\.gnome\.Calculator|gnome-calculator)$
windowrulev2 = float, title:^(Picture-in-Picture|Volume Control|Bluetooth Devices)$
windowrulev2 = center, class:^(Toplevel|pavucontrol|org\.pulseaudio\.pavucontrol|org\.gnome\.Calculator)$
windowrulev2 = float, class:^(rofi|Rofi|\.rofi-wrapped)$
windowrulev2 = noborder, class:^(rofi|Rofi|\.rofi-wrapped)$
windowrulev2 = nofocus, class:^(rofi|Rofi|\.rofi-wrapped|screenkey|Screenkey)$
windowrulev2 = noblur, class:^(screenkey|Screenkey)$
windowrulev2 = float, class:^(pinentry-gnome-3|pinentry-qt)$
windowrulev2 = center, class:^(pinentry-gnome-3|pinentry-qt)$
windowrulev2 = float, class:^(xdg-desktop-portal-gtk|xdg-desktop-portal)$
windowrulev2 = noblur, class:^(steam_app|Steam|steam)$
windowrulev2 = opaque, class:^(steam_app)$
windowrulev2 = fullscreenstate 2 2, class:^(steam_app)$
